Update deploy.yml
first one failed due to npm error Missing script: "build"
npm error
npm error To see a list of scripts, run:
npm error npm run
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2025-06-30T05_00_27_784Z-debug-0.log
Error: Process completed with exit code 1.

This supposedly fixes it